version: "3"
services:
  yunzai:
    container_name: miao-yunzai
    build:                                                               # 使用 Dockerfile 本地构建
      context: ./docker
      args:
        BUNDLE_FFMPEG: 'false'                                           # 是否在构建时打包 ffmpeg
        BUNDLE_POETRY: 'false'                                           # 是否在构建时打包 poetry
        USE_APT_MIRROR: 'false'                                          # 是否在构建时使用 apt 镜像
        USE_NPM_MIRROR: 'false'                                          # 是否在构建时使用 npm 镜像
        USE_PYPI_MIRROR: 'false'                                         # 是否在构建时使用 pypi 镜像
        INSTALL_GUOBA: 'true'                                            # 是否在构建时安装锅巴插件
    restart: always
    hostname: miao-yunzai
    ports:
      - "2536:2536"                                                      # 映射锅巴插件端口，格式"主机端口:容器内部端口"
    volumes:
      - ./yunzai/config:/app/TRSS-Yunzai/config                          # Bot配置文件
      - ./yunzai/logs:/app/TRSS-Yunzai/logs                              # 日志文件
      - ./yunzai/data:/app/TRSS-Yunzai/data                              # 数据文件
      - ./yunzai/temp:/app/TRSS-Yunzai/temp                              # 临时文件
      - ./yunzai/plugins:/app/TRSS-Yunzai/plugins                        # 插件目录
    depends_on:
      redis:
        condition: service_healthy
      lagrange:
        condition: service_started

  redis:
    container_name: miao-redis
    image: redis:alpine
    hostname: miao-redis
    restart: always
    volumes:
      # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中
      # - ./redis/config:/etc/redis/    # Redis配置文件
      - ./yunzai/redis/data:/data
      - ./yunzai/redis/logs:/logs
    # command: /etc/redis/redis.conf    # 取消注释以应用Redis配置文件
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s

  lagrange:
    container_name: miao-lagrange
    image: ghcr.io/lagrangedev/lagrange.onebot:edge
    hostname: miao-lagrange
    restart: always
    volumes:
      - ./yunzai/lagrange:/app/data
